[package]
name = "matching_programming_languages"
version = "0.1.0"
edition = "2021"
include = ["resources"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["image"] }
iced_native = "0.10.3"